---
# tasks file for wordpress
    - name: 'check wordpress exist or not'
      stat: path=/var/www/wordpress
      register: wordpress_path_check

    - name: download and unarchive wordpress
      unarchive:
              src: http://wordpress.org/latest.tar.gz
              dest: /var/www/
              remote_src: yes
      when: not wordpress_path_check.stat.exists

    - name: change wordpress folder ownership
      file:
              path: /var/www/wordpress
              owner: www-data
              group: www-data
      become: yes
